# Recreating Gradient Descent Algorithm with TensorFlow 2.0

#### All needed imports

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import matplotlib.pyplot as plt

## We will simulate the following formula: 2*X -7*W + Bias

### Generating data

In [2]:
observations = 25000

X = np.random.uniform(low = -10, high = 10, size = (observations, 1))
W = np.random.uniform(low = -10, high = 10, size = (observations, 1))

INPUTS = np.column_stack((X, W))

noise = np.random.uniform(low = -1, high = 1, size = (observations, 1))

In [3]:
X, X.shape

(array([[-2.62299213],
        [ 4.64955799],
        [ 4.28726575],
        ...,
        [ 2.33593824],
        [-3.0926153 ],
        [ 3.29312211]]), (25000, 1))

In [4]:
W, W.shape

(array([[ 9.26464939],
        [-5.94606681],
        [ 2.30662044],
        ...,
        [ 6.36647994],
        [ 0.52967216],
        [-9.45511758]]), (25000, 1))

In [5]:
INPUTS, INPUTS.shape

(array([[-2.62299213,  9.26464939],
        [ 4.64955799, -5.94606681],
        [ 4.28726575,  2.30662044],
        ...,
        [ 2.33593824,  6.36647994],
        [-3.0926153 ,  0.52967216],
        [ 3.29312211, -9.45511758]]), (25000, 2))

In [6]:
noise, noise.shape

(array([[-0.13851105],
        [-0.06652155],
        [ 0.27689163],
        ...,
        [-0.00527711],
        [ 0.25470859],
        [-0.58796814]]), (25000, 1))

In [7]:
TARGETS = 2*X - 7*W + 10 + noise
TARGETS

array([[-60.23704107],
       [ 60.85506211],
       [  2.70508009],
       ...,
       [-29.8987602 ],
       [  0.36177286],
       [ 82.18409913]])

#### Saving generated Data

In [8]:
np.savez('TF_INTRO', inputs=INPUTS, targets=TARGETS)

### Building the Model

#### Loading Data

In [9]:
training_data = np.load('TF_INTRO.npz')

#### Variables that measure the size of our inputs and outputs

In [10]:
input_size = 2
output_size = 1

#### Building the Model

1. <i>Sequential</i> specifies how the model will be laid down (stacked)


2. <i>Dense</i> layer takes the inputs provided to the model and calculates the dot product of the inputs and the weights and adds bias. 

FROM TENSORFLOW DOCS: `Dense` implements the operation:
`output = activation(dot(input, kernel) + bias)`
where `activation` is the element-wise activation function
passed as the `activation` argument, `kernel` is a weights matrix
created by the layer, and `bias` is a bias vector created by the layer

In [11]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(output_size)
])

# configuring the model for training
model.compile(optimizer='SGD', loss='mean_squared_error')

model.fit(training_data['inputs'], training_data['targets'], epochs = 100, verbose = 0)

Setting <i>verbose = 0</i> makes the model "silent", thus no output is given

Set <i>verbose</i> to "2" to obtain one-line-output

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                multiple                  3         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.fit(training_data['inputs'], training_data['targets'], epochs = 100, verbose = 1)

Train on 25000 samples
Epoch 1/100
25000/25000 [==============================] - 0s 20us/sample - loss: 0.3464
Epoch 2/100
25000/25000 [==============================] - 0s 19us/sample - loss: 0.3463
Epoch 3/100
25000/25000 [==============================] - 0s 19us/sample - loss: 0.3459
Epoch 4/100
25000/25000 [==============================] - 0s 18us/sample - loss: 0.3469
Epoch 5/100
25000/25000 [==============================] - 0s 19us/sample - loss: 0.3457
Epoch 6/100
25000/25000 [==============================] - 1s 28us/sample - loss: 0.3457
Epoch 7/100
25000/25000 [==============================] - 0s 18us/sample - loss: 0.3482
Epoch 8/100
25000/25000 [==============================] - 0s 19us/sample - loss: 0.3476
Epoch 9/100
25000/25000 [==============================] - 0s 19us/sample - loss: 0.3454
Epoch 10/100
25000/25000 [==============================] - 0s 19us/sample - loss: 0.3474
Epoch 11/100
25000/25000 [==============================] - 0s 19us/sample - loss: 0.3

25000/25000 [==============================] - 0s 19us/sample - loss: 0.3468
Epoch 92/100
25000/25000 [==============================] - 0s 19us/sample - loss: 0.3476
Epoch 93/100
25000/25000 [==============================] - 0s 19us/sample - loss: 0.3461
Epoch 94/100
25000/25000 [==============================] - 0s 19us/sample - loss: 0.3445
Epoch 95/100
25000/25000 [==============================] - 0s 18us/sample - loss: 0.3456
Epoch 96/100
25000/25000 [==============================] - 0s 19us/sample - loss: 0.3463
Epoch 97/100
25000/25000 [==============================] - 1s 21us/sample - loss: 0.3457
Epoch 98/100
25000/25000 [==============================] - 1s 22us/sample - loss: 0.3453
Epoch 99/100
25000/25000 [==============================] - 0s 19us/sample - loss: 0.3458
Epoch 100/100
25000/25000 [==============================] - 0s 18us/sample - loss: 0.3462


### Extracting weights and biases

Output is a tensor with two arrays - one for the weights, one for the biases

In [27]:
model.layers[0].get_weights()

[array([[ 1.9937725],
        [-7.0247025]], dtype=float32), array([10.006209], dtype=float32)]

### It worked great!

### Extracting the outputs, making predictions

In [28]:
model.predict_on_batch(training_data['inputs'])

array([[ -0.4158182 ],
       [ 69.27829   ],
       [  0.45665264],
       ...,
       [ 22.525946  ],
       [ 21.836842  ],
       [-48.28674   ]], dtype=float32)

In [30]:
training_data['targets']

array([[  0.09531858],
       [ 69.86728164],
       [  1.26979627],
       ...,
       [ 23.57069651],
       [ 21.64203904],
       [-47.23952255]])

In [31]:
model.evaluate(training_data['inputs'])

782/782 [==============================] - 0s 292us/step - loss: 0.0000e+00


0.0

## Customizing the Model

In [39]:
keras.backend.clear_session()

In [40]:
model_ctd = tf.keras.Sequential([
    tf.keras.layers.Dense(output_size, kernel_initializer = tf.random_uniform_initializer(-0.1, 0.1),
                         bias_initializer = tf.random_uniform_initializer(-0.1, 0.1))
])

custom_optimizer = tf.keras.optimizers.SGD(learning_rate=0.002)

model_ctd.compile(optimizer=custom_optimizer, loss='huber_loss')

model_ctd.fit(training_data['inputs'], training_data['targets'], epochs = 100)

Epoch 1/100
782/782 [==============================] - 0s 380us/step - loss: 19.4619
Epoch 2/100
782/782 [==============================] - 0s 347us/step - loss: 8.1281
Epoch 3/100
782/782 [==============================] - 0s 359us/step - loss: 6.5811
Epoch 4/100
782/782 [==============================] - 0s 348us/step - loss: 5.0436
Epoch 5/100
782/782 [==============================] - 0s 348us/step - loss: 3.5071
Epoch 6/100
782/782 [==============================] - 0s 349us/step - loss: 1.9735
Epoch 7/100
782/782 [==============================] - 0s 347us/step - loss: 0.6516
Epoch 8/100
782/782 [==============================] - 0s 349us/step - loss: 0.2131
Epoch 9/100
782/782 [==============================] - 0s 361us/step - loss: 0.1701
Epoch 10/100
782/782 [==============================] - 0s 367us/step - loss: 0.1677
Epoch 11/100
782/782 [==============================] - 0s 364us/step - loss: 0.1676
Epoch 12/100
782/782 [==============================] - 0s 355us/step - l

In [41]:
model.layers[0].get_weights()

[array([[ 1.9937725],
        [-7.0247025]], dtype=float32), array([10.006209], dtype=float32)]

### Loss is much smaller!